// <auto-generated />
namespace NasleGhalam.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class questionanswer_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(questionanswer_change));
        
        string IMigrationMetadata.Id
        {
            get { return "202101250830562_questionanswer_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
