// <auto-generated />
namespace NasleGhalam.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateLessonFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateLessonFile));
        
        string IMigrationMetadata.Id
        {
            get { return "202201311446024_updateLessonFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
