//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlinekhan.SSO.Service.SmsPanelService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsPanelService.FastSendSoap")]
    public interface FastSendSoap {
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoSendCode", ReplyAction="*")]
        Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeResponse AutoSendCode(Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoSendCode", ReplyAction="*")]
        System.Threading.Tasks.Task<Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeResponse> AutoSendCodeAsync(Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageWithCode", ReplyAction="*")]
        Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeResponse SendMessageWithCode(Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageWithCode", ReplyAction="*")]
        System.Threading.Tasks.Task<Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeResponse> SendMessageWithCodeAsync(Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckSendCode", ReplyAction="*")]
        Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeResponse CheckSendCode(Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckSendCode", ReplyAction="*")]
        System.Threading.Tasks.Task<Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeResponse> CheckSendCodeAsync(Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoSendCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoSendCode", Namespace="http://tempuri.org/", Order=0)]
        public Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeRequestBody Body;
        
        public AutoSendCodeRequest() {
        }
        
        public AutoSendCodeRequest(Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoSendCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReciptionNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Footer;
        
        public AutoSendCodeRequestBody() {
        }
        
        public AutoSendCodeRequestBody(string Username, string Password, string ReciptionNumber, string Footer) {
            this.Username = Username;
            this.Password = Password;
            this.ReciptionNumber = ReciptionNumber;
            this.Footer = Footer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoSendCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoSendCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeResponseBody Body;
        
        public AutoSendCodeResponse() {
        }
        
        public AutoSendCodeResponse(Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoSendCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long AutoSendCodeResult;
        
        public AutoSendCodeResponseBody() {
        }
        
        public AutoSendCodeResponseBody(long AutoSendCodeResult) {
            this.AutoSendCodeResult = AutoSendCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageWithCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageWithCode", Namespace="http://tempuri.org/", Order=0)]
        public Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeRequestBody Body;
        
        public SendMessageWithCodeRequest() {
        }
        
        public SendMessageWithCodeRequest(Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageWithCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReciptionNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Code;
        
        public SendMessageWithCodeRequestBody() {
        }
        
        public SendMessageWithCodeRequestBody(string Username, string Password, string ReciptionNumber, string Code) {
            this.Username = Username;
            this.Password = Password;
            this.ReciptionNumber = ReciptionNumber;
            this.Code = Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageWithCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageWithCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeResponseBody Body;
        
        public SendMessageWithCodeResponse() {
        }
        
        public SendMessageWithCodeResponse(Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageWithCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long SendMessageWithCodeResult;
        
        public SendMessageWithCodeResponseBody() {
        }
        
        public SendMessageWithCodeResponseBody(long SendMessageWithCodeResult) {
            this.SendMessageWithCodeResult = SendMessageWithCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckSendCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckSendCode", Namespace="http://tempuri.org/", Order=0)]
        public Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeRequestBody Body;
        
        public CheckSendCodeRequest() {
        }
        
        public CheckSendCodeRequest(Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckSendCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReciptionNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Code;
        
        public CheckSendCodeRequestBody() {
        }
        
        public CheckSendCodeRequestBody(string Username, string Password, string ReciptionNumber, string Code) {
            this.Username = Username;
            this.Password = Password;
            this.ReciptionNumber = ReciptionNumber;
            this.Code = Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckSendCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckSendCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeResponseBody Body;
        
        public CheckSendCodeResponse() {
        }
        
        public CheckSendCodeResponse(Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckSendCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckSendCodeResult;
        
        public CheckSendCodeResponseBody() {
        }
        
        public CheckSendCodeResponseBody(bool CheckSendCodeResult) {
            this.CheckSendCodeResult = CheckSendCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FastSendSoapChannel : Onlinekhan.SSO.Service.SmsPanelService.FastSendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FastSendSoapClient : System.ServiceModel.ClientBase<Onlinekhan.SSO.Service.SmsPanelService.FastSendSoap>, Onlinekhan.SSO.Service.SmsPanelService.FastSendSoap {
        
        public FastSendSoapClient() {
        }
        
        public FastSendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FastSendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FastSendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FastSendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeResponse Onlinekhan.SSO.Service.SmsPanelService.FastSendSoap.AutoSendCode(Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeRequest request) {
            return base.Channel.AutoSendCode(request);
        }
        
        public long AutoSendCode(string Username, string Password, string ReciptionNumber, string Footer) {
            Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeRequest inValue = new Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeRequest();
            inValue.Body = new Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            inValue.Body.Footer = Footer;
            Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeResponse retVal = ((Onlinekhan.SSO.Service.SmsPanelService.FastSendSoap)(this)).AutoSendCode(inValue);
            return retVal.Body.AutoSendCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeResponse> Onlinekhan.SSO.Service.SmsPanelService.FastSendSoap.AutoSendCodeAsync(Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeRequest request) {
            return base.Channel.AutoSendCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeResponse> AutoSendCodeAsync(string Username, string Password, string ReciptionNumber, string Footer) {
            Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeRequest inValue = new Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeRequest();
            inValue.Body = new Onlinekhan.SSO.Service.SmsPanelService.AutoSendCodeRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            inValue.Body.Footer = Footer;
            return ((Onlinekhan.SSO.Service.SmsPanelService.FastSendSoap)(this)).AutoSendCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeResponse Onlinekhan.SSO.Service.SmsPanelService.FastSendSoap.SendMessageWithCode(Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeRequest request) {
            return base.Channel.SendMessageWithCode(request);
        }
        
        public long SendMessageWithCode(string Username, string Password, string ReciptionNumber, string Code) {
            Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeRequest inValue = new Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeRequest();
            inValue.Body = new Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            inValue.Body.Code = Code;
            Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeResponse retVal = ((Onlinekhan.SSO.Service.SmsPanelService.FastSendSoap)(this)).SendMessageWithCode(inValue);
            return retVal.Body.SendMessageWithCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeResponse> Onlinekhan.SSO.Service.SmsPanelService.FastSendSoap.SendMessageWithCodeAsync(Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeRequest request) {
            return base.Channel.SendMessageWithCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeResponse> SendMessageWithCodeAsync(string Username, string Password, string ReciptionNumber, string Code) {
            Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeRequest inValue = new Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeRequest();
            inValue.Body = new Onlinekhan.SSO.Service.SmsPanelService.SendMessageWithCodeRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            inValue.Body.Code = Code;
            return ((Onlinekhan.SSO.Service.SmsPanelService.FastSendSoap)(this)).SendMessageWithCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeResponse Onlinekhan.SSO.Service.SmsPanelService.FastSendSoap.CheckSendCode(Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeRequest request) {
            return base.Channel.CheckSendCode(request);
        }
        
        public bool CheckSendCode(string Username, string Password, string ReciptionNumber, string Code) {
            Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeRequest inValue = new Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeRequest();
            inValue.Body = new Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            inValue.Body.Code = Code;
            Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeResponse retVal = ((Onlinekhan.SSO.Service.SmsPanelService.FastSendSoap)(this)).CheckSendCode(inValue);
            return retVal.Body.CheckSendCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeResponse> Onlinekhan.SSO.Service.SmsPanelService.FastSendSoap.CheckSendCodeAsync(Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeRequest request) {
            return base.Channel.CheckSendCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeResponse> CheckSendCodeAsync(string Username, string Password, string ReciptionNumber, string Code) {
            Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeRequest inValue = new Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeRequest();
            inValue.Body = new Onlinekhan.SSO.Service.SmsPanelService.CheckSendCodeRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            inValue.Body.Code = Code;
            return ((Onlinekhan.SSO.Service.SmsPanelService.FastSendSoap)(this)).CheckSendCodeAsync(inValue);
        }
    }
}
