// <auto-generated />
namespace NasleGhalam.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fix_questionasnwer_judge_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_questionasnwer_judge_field));
        
        string IMigrationMetadata.Id
        {
            get { return "202006220609443_fix_questionasnwer_judge_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
